### ISSUE TITLE
ATL Java Evaluation

### ISSUE THREAD

**Issue by eicke123** [martin-fleck/cra-ttc2016#10]
[EvaluationSheet ATL.xlsx](https://github.com/martin-fleck/cra-ttc2016/files/279668/EvaluationSheet.ATL.xlsx)

cu

**Comment by georghinkel** [comment]
I think there is something wrong, because the evaluation sheet seems to be the unmodified reference evaluation sheet for an "Example solution" with full points.

**Comment by fikovnik** [comment]
@eicke123 Could you please check the evaluation sheet and post it here again. Thanks!
